Feature: Add About Page
dev-protocol/devprotocol.xyz pull request #192
Opened 2021-12-09 15:18 UTC by AbhinavMV

#### Description of the change

Added about page
- Added in navbar (overview)
- Removed Teams Section from developer page
- Removed Q&A from FAQ

Closes #189 

#### Screenshots
![image](https://user-images.githubusercontent.com/35369843/145423119-9916de35-acc7-4ff9-bb8d-4fe3aa98a624.png)

#### Checklist

**I agree to the following :-**

* [x]   Added description of the change
* [x]   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
* [x]   Search previous suggestions before making a new PR, as yours may be a duplicate.
* [x]   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 
Let me know if any changes are needed or if you have a better design in mind. 😄

2021-12-09 16:58 UTC, Panquesito7 requested changes

2021-12-09 16:58 UTC, Panquesito7 commented on src/components/About/About.astro
> +</section>
Missing an endline.
```suggestion
</section>

```

2021-12-09 16:58 UTC, Panquesito7 commented on src/components/About/About.astro
> +        This is just a description of the basic components of the Dev Protocol ecosystem. There are many possible use cases for this new economic infrastructure designed for creators, so please try i
```suggestion
        <p>The positive cycle created by Public goods such as OSS begins sustainability and enables more OSS developers, artists, researchers, and other creators to live independently. To collaborate with more projects freely is the greatest value for all.<br/><br/>
        The core features of Dev Protocol are evaluation, distribution, and management for the creator's projects. By using Dev Protocol, even a small, newly started project can increase its evaluation and improve its market capitalization. The ability to achieve this has been limited to stock companies now, but Dev Protocol is opening up that possibility to all creators.<br/><br/>
        The first step for creators is to prove their ownership of the project and issue their property tokens(ERC-20). Once issue tokens, creators can monetize through staking by supporters, share and divide them with their co-developers. In addition, these tokens allow creators to give partial ownership to all the contributors involved in the OSS development to provide a sustainable opportunity for profit without the need for token sales.<br/><br/>
        This is just a description of the basic components of the Dev Protocol ecosystem. There are many possible use cases for this new economic infrastructure designed for creators, so please try it out for yourself!</p>
```

2021-12-09 16:58 UTC, Panquesito7 commented on src/pages/about.astro
> +<Layout metaTitle="Developers | Dev Protocol">
```suggestion
<Layout metaTitle="About us | Dev Protocol">
```

2021-12-09 17:25 UTC, AbhinavMV commented on src/pages/about.astro
> +<Layout metaTitle="Developers | Dev Protocol">
Done

2021-12-09 17:25 UTC, AbhinavMV commented on src/components/About/About.astro
> +        This is just a description of the basic components of the Dev Protocol ecosystem. There are many possible use cases for this new economic infrastructure designed for creators, so please try i
Done

2021-12-09 17:25 UTC, AbhinavMV commented on src/components/About/About.astro
> +</section>
Done

2021-12-09 17:48 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-10 00:06 UTC, vinzvinci approved these changes
LGTM 👍

2021-12-10 03:13 UTC, krishguptadev approved these changes

2021-12-10 03:14 UTC, merged